name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest tag
        run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)

      - name: Bump version
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_tag.outputs.tag }}"
          echo "Current version: $major.$minor.$patch"
          echo "Bumping patch version..."
          echo "::set-output name=version::$major.$minor.$((patch + 1))"

      - name: Create release
        run: |
          gh release create ${{ steps.bump_version.outputs.version }} --title ${{ steps.bump_version.outputs.version }}
